# --- Ini del programa meteo autor Binarybiker 2026


# --- Esta es la configuracion de la placa que estamos usando ---
# --- Una ESP8266 Wemos D1 Mini clonica o generica ----
[env:d1_mini]
platform = espressif8266 # -- Placa
board = d1_mini          # -- Modelo
framework = arduino      # -- Entorno
upload_port = /dev/ttyUSB0 # -- Donde esta conectada la placa al PC. "Esto es para linux"
monitor_speed = 115200   # -- Velocidad del puesto serie
# --- Algunas de las configuraciones anteriores pueden resultar un poco redundantes
# --- como el puerto o la velocidad, seguramente se puede cargar el programa sin ser
# --- tan expllicito pero a veces VS Code es un poco quisquilloso


lib_deps =
    # --- Aqui las librerias que estamos usando ---
    adafruit/Adafruit SSD1306 @ ^2.5.9
    adafruit/Adafruit GFX Library @ ^1.11.9
    adafruit/Adafruit BusIO @ ^1.14.5
    
    # --- Aqui las librerias que gestionan el clima ---
    bblanchon/ArduinoJson @ ^6.21.3
    # (La de WiFi y HTTP ya vienen en el core de ESP8266)